theme = "hyde"
archetypeDir = "archetypes"
contentDir = "content"
layoutDir = "layouts"
publishDir = "docs"
buildDrafts = true
baseURL = "http://thelaurence.com/"
title = "laurence's website"
canonifyURLs = "false"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Just a place to post some things."
  copyright = "Laurence Glazier"